github: [Lalatenduswain]
patreon: lalatenduswain
tidelift: lalatendu/swain
custom: ["https://www.paypal.com/paypalme/lalatenduswain", https://buymeacoffee.com/lalatendu.swain]
#custom: ["https://www.paypal.com/paypalme/lalatenduswain", https://lalatenndu.info]
